NCNN_MP_MOD_DIR := $(USERMOD_DIR)
NCNN_DIR := $(NCNN_MP_MOD_DIR)/../../ncnn
NCNN_BUILD_DIR := $(NCNN_DIR)/build/src

SRC_USERMOD_C += $(NCNN_MP_MOD_DIR)/ncnn_mp.c

CXXFLAGS_USERMOD += -I$(NCNN_DIR)/src
CFLAGS_USERMOD += -I$(NCNN_DIR)/src
CXXFLAGS_USERMOD += -I$(NCNN_BUILD_DIR)
CFLAGS_USERMOD += -I$(NCNN_BUILD_DIR)

CXXFLAGS_USERMOD += -std=c++11
CFLAGS_USERMOD += -Wno-unused-function
CXXFLAGS_USERMOD += -Wno-unused-function

LDFLAGS_USERMOD += -L$(NCNN_BUILD_DIR)
LDFLAGS_USERMOD += -lncnn
LDFLAGS_USERMOD += -lstdc++