NCNN_MP_DIR := $(USERMOD_DIR)
NCNN_SRC_DIR := $(NCNN_MP_DIR)/../ncnn/src

NCNN_CORE_SRC := $(wildcard $(NCNN_SRC_DIR)/*.cpp)
NCNN_CORE_SRC := $(filter-out %/vulkan%, $(NCNN_CORE_SRC))
NCNN_CORE_SRC := $(filter-out %/vulkan.cpp, $(NCNN_CORE_SRC))

NCNN_ALL_LAYER_SRC := $(shell find $(NCNN_SRC_DIR)/layer -name '*.cpp')
NCNN_ALL_LAYER_SRC := $(filter-out %/vulkan/%, $(NCNN_ALL_LAYER_SRC))
NCNN_ALL_LAYER_SRC := $(filter-out %/x86/%, $(NCNN_ALL_LAYER_SRC))

SRC_USERMOD_C += $(NCNN_MP_DIR)/ncnn_mp.c
SRC_USERMOD_LIB_CXX += $(NCNN_CORE_SRC)
SRC_USERMOD_LIB_CXX += $(NCNN_ALL_LAYER_SRC)

CFLAGS_USERMOD  += -I$(NCNN_SRC_DIR)
CXXFLAGS_USERMOD += -I$(NCNN_SRC_DIR)

CXXFLAGS_USERMOD += -DNCNN_VULKAN=0
CXXFLAGS_USERMOD += -DNCNN_BUILD_TOOLS=0
CXXFLAGS_USERMOD += -DNCNN_BUILD_EXAMPLES=0
CXXFLAGS_USERMOD += -DNCNN_BUILD_BENCHMARK=0
CXXFLAGS_USERMOD += -DNCNN_BUILD_TESTS=0
CXXFLAGS_USERMOD += -DNCNN_PYTHON=0
CXXFLAGS_USERMOD += -DNCNN_STDIO=1
CXXFLAGS_USERMOD += -DNCNN_STRING=1
CXXFLAGS_USERMOD += -DNCNN_PIXEL=1
CXXFLAGS_USERMOD += -DNCNN_SIMPLEOMP=1
CXXFLAGS_USERMOD += -DNCNN_SIMPLESTL=1
CXXFLAGS_USERMOD += -DNCNN_DISABLE_RTTI=1
CXXFLAGS_USERMOD += -DNCNN_DISABLE_EXCEPTION=1
